<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>Python on 大海里的木鱼</title><link>https://www.pigflying.net/tags/python/</link><description>Recent content in Python on 大海里的木鱼</description><generator>Hugo</generator><language>zh-hans</language><lastBuildDate>Sun, 16 Jun 2013 09:34:00 +0800</lastBuildDate><atom:link href="https://www.pigflying.net/tags/python/index.xml" rel="self" type="application/rss+xml"/><item><title>python中的默认递归深度</title><link>https://www.pigflying.net/post/2013-06-16-python-recursion-limit/</link><pubDate>Sun, 16 Jun 2013 09:34:00 +0800</pubDate><guid>https://www.pigflying.net/post/2013-06-16-python-recursion-limit/</guid><description>&lt;p>使用python中出现了一个很奇怪的异常，&lt;code>RuntimeError: maximum recursion depth exceeded in cmp&lt;/code>，原来是递归引起的。看一个简单的例子，factorial数列。&lt;/p>
&lt;pre>&lt;code class="language-python">
#!/usr/bin/python#
-*- coding: utf-8 -*-

def factorial(n): 
 if n == 0 or n == 1: 
 return 1 
 else: 
 return n * factorial(n - 1)
if __name__ == ''__main__'': 
 factorial(1000)

&lt;/code>&lt;/pre>
&lt;p>这个例子就会引起这个RuntimeError,原因是python中默认的递归深度的限制，默认的是1000， 我使用的是python2.7.3。
使用sys可以查看和修改当前环境下默认递归深度，参见 &lt;a href="http://docs.python.org/2/library/sys.html#sys.getrecursionlimitimport" target="_blank">recursionlimit&lt;/a>{:target=&amp;quot;_blank&amp;quot;}&lt;/p></description></item></channel></rss>